version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: denning_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-denning}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-denningpass}
      POSTGRES_DB: ${POSTGRES_DB:-denning_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U denning"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - denning_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: denning_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://denning:denningpass@postgres:5432/denning_db?schema=public
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npm start"
    networks:
      - denning_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: denning_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@denning.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - denning_network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  denning_network:
    driver: bridge 